#spring.mail.host=smtp.qiye.163.com //邮箱服务器地址
#spring.mail.username=xxx@oo.com //用户名
#spring.mail.password=xxyyooo    //密码
#spring.mail.default-encoding=UTF-8
#
#mail.fromMail.addr=xxx@oo.com  //以谁来发送邮件

spring:
  mail:
    host: smtp.163.com # 发件服务器地址,不同邮件平台地址不同
    #port: 25 #常用邮件端口25、109、110、143、465、995、993、994 如果开启了SSL安全则使用对应的端口号，25为非加密端口号
    username: yangjian2628168@163.com #发送邮件的账号
    password: OMPNJDPRLDGQAAUK #发送邮件账号的授权码,这里的授权码不是验证码.需要到邮箱
    default-encoding: utf-8 #设置编码
    properties: # 设置邮件超时时间防止服务器阻塞
      timeout: 5000
      connection-timeout: 5000
      write-timeout: 5000
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


  servlet:
    multipart:
      max-file-size: 1GB # 用于设置上传文件的最大大小，默认值为1MB。如果上传的文件大小超过这个限制，则会导致上传失败
      max-request-size: 2GB # 参数用于设置整个请求的最大大小，包括所有文件和表单数据，默认值为10MB。如果请求大小超过这个限制，Spring Boot 将拒绝接收请求，并返回一个异常

mail:
  fromMail:
    addr: yangjian2628168@163.com