spring:
  data:
    redis:
      host: 192.168.56.11  # Redis服务器的主机名或IP地址，默认为localhost
      port: 6379           # Redis服务器的端口号，默认为6379
#      ssl:
#        enabled: false    # Redis服务器使用SSL连接，默认为false
#        bundle: example   # 启用了 SSL 加密，并指定了证书文件名为 "example"
#      database: 1          # 要连接的Redis数据库编号，默认为0
#      username: root      # 用于连接Redis服务器的用户名，如果不需要身份验证，可以省略此属性。
#      password: 123456    # 用于连接Redis服务器的密码，如果不需要身份验证，可以省略此属性。

